server:
  port: 8883
  path: /family
spring:
  datasource:
    druid:
      url: jdbc:mysql://10.10.8.205:3306/t_test?useUnicode=true&characterEncoding=utf8
      username: caocao
      password: caocao123
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10
      filters: 'stat,wall'
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
         enabled: true
         url-pattern: /*
         exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
      stat-view-servlet:
         enabled: true
         url-pattern: /druid/*
         reset-enable: true
         login-username: rongly
         login-password: pxm88888
  application:
    name: zupu-family
  redis:
    cluster.nodes:
      - 10.10.3.71:7000
      - 10.10.3.71:7001
      - 10.10.3.71:7002
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
#json时间戳返回
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#  thymeleaf:
#  cach: false

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lv.zupu.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #mp2.3+ 全局表前缀 mp_
    table-prefix: zupu_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    #jdbc-type-for-null: 'null'
logging:
    level:
        root: info
        org.springframework.web: info
        org.apache.ibatis: warn
    path: "./logs"

